set( APPLICATION_NAME           "Example Branding" )
set( APPLICATION_SHORTNAME      "example" )
set( APPLICATION_DOMAIN         "example.fr" )
set( APPLICATION_VENDOR         "Example Branding" )
set( APPLICATION_UPDATE_URL     "https://www.example.fr/updater" )
set( APPLICATION_HELP_URL       "https://www.example.fr/wiki" )
set( APPLICATION_REGISTER_URL   "https://www.example.fr/register" )
set( APPLICATION_CLOUD_URL      "https://www.example.fr/cloud" )
set( APPLICATION_REV_DOMAIN     "fr.example.desktopclient" )
set( NEXTCLOUD_BACKGROUND_COLOR "#cc3216" )