set( APPLICATION_NAME           "IDF Cloud" )
set( APPLICATION_SHORTNAME      "idfcloud" )
set( APPLICATION_DOMAIN         "iledefrance.fr" )
set( APPLICATION_VENDOR         "Ile de France" )
set( APPLICATION_UPDATE_URL     "https://www.iledefrance.fr/updater" )
set( APPLICATION_HELP_URL       "https://www.iledefrance.fr/wiki" )
set( APPLICATION_REGISTER_URL   "https://www.iledefrance.fr/admin" )
set( APPLICATION_CLOUD_URL      "https://www.iledefrance.fr/cloud" )
set( APPLICATION_REV_DOMAIN     "fr.iledefrance.desktopclient" )
set( NEXTCLOUD_BACKGROUND_COLOR "#cc3216" )