set( APPLICATION_NAME           "IDF Cloud" )
set( APPLICATION_SHORTNAME      "idfcloud" )
set( APPLICATION_DOMAIN         "iledefrance.fr" )
set( APPLICATION_VENDOR         "Ile de France" )
set( APPLICATION_UPDATE_URL     "https://www.iledefrance.fr/updater" CACHE STRING "URL for updater" )
set( APPLICATION_HELP_URL       "https://www.iledefrance.fr/wiki" CACHE STRING "URL for the help menu" )
set( APPLICATION_REGISTER_URL   "https://www.iledefrance.fr/admin" CACHE STRING "URL to register" )
set( APPLICATION_CLOUD_URL      "https://www.iledefrance.fr/cloud" CACHE STRING "URL to your cloud" )
set( APPLICATION_REV_DOMAIN     "fr.iledefrance.desktopclient" )
set( NEXTCLOUD_BACKGROUND_COLOR "#cc3216" CACHE STRING "Default Nextcloud background color")